### PR TITLE
wip: adding updated scripts/terraform

### PR DESCRIPTION
**Pull request by jonahjon**

### CODE REVIEW

**Comment by maxgio92** [comment]
Managed nodes... Great idea!

**Comment by maxgio92** [comment]
I think that the README after that will need to be updated with the new requirements (`terraform` and `awscli` binaries for sure for now) and maybe steps

**Comment by jonahjon** [comment]
> I think that the README after that will need to be updated with the new requirements (`terraform` and `awscli` binaries for sure for now) and maybe steps

I agree, will add those in the PR too

**Comment by maxgio92** [comment]
Ops! No Prow here :(

**Comment by maxgio92** [comment]
Converged in main PR [#188](https://github.com/falcosecurity/test-infra/pull/188)

**Pull request merged**
